[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "~/.kube/config-rwml-dev"

[tools]
python = "3.12"
# Essential tools (optimized for speed)
"aqua:kubernetes/kubectl" = "1.32.3"
"aqua:helm/helm" = "3.17.2"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:derailed/k9s" = "0.40.10"
"aqua:pre-commit/pre-commit" = "3.7.0"
# Optional tools (install manually if needed)
# "aqua:mikefarah/yq" = "4.45.1"
# "aqua:ahmetb/kubectx" = "0.9.5"
# "aqua:digitalocean/doctl" = "1.104.0"
