apiVersion: batch/v1
kind: Job
metadata:
  name: mlflow-db-init
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 60  # Clean up 60 seconds after completion
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:15
        command:
        - /bin/bash
        - -c
        - |
          echo "Setting up MLFlow database and user..."
          PGPASSWORD=postgres psql -h risingwave-postgresql.risingwave.svc.cluster.local -U postgres -c "CREATE USER mlflow WITH PASSWORD 'mlflow';" || echo "User mlflow already exists"
          PGPASSWORD=postgres psql -h risingwave-postgresql.risingwave.svc.cluster.local -U postgres -c "CREATE DATABASE mlflow OWNER mlflow;" || echo "Database mlflow already exists"
          PGPASSWORD=postgres psql -h risingwave-postgresql.risingwave.svc.cluster.local -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE mlflow TO mlflow;" || echo "Privileges already granted"
          echo "Database setup complete!"
        env:
        - name: PGPASSWORD
          value: "postgres"
      restartPolicy: Never
  backoffLimit: 3
