apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators
  namespace: services
  labels:
    app: technical-indicators
spec:
  replicas: 2
  selector:
    matchLabels:
      app: technical-indicators
  template:
    metadata:
      labels:
        app: technical-indicators
    spec:
      containers:
      - name: technical-indicators
        image: technical-indicators:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "candles"
        - name: KAFKA_OUTPUT_TOPIC
          value: "technical_indicators"
        - name: KAFKA_CONSUMER_GROUP
          value: "technical_indicators_consumer_group"
        - name: CANDLE_SECONDS
          value: "60"
        - name: RISINGWAVE_HOST
          value: "risingwave.risingwave.svc.cluster.local"
        - name: RISINGWAVE_PORT
          value: "4567"
        - name: RISINGWAVE_USER
          value: "root"
        - name: RISINGWAVE_DATABASE
          value: "dev"
        - name: RISINGWAVE_PASSWORD
          value: "123456"
        - name: RISINGWAVE_TABLE_NAME
          value: "technical_indicators"
