---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  namespace: apps
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: trades
        image: ghcr.io/ajavelosa/trades:0.0.1-beta.1745389345
        imagePullPolicy: Always
        #
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-c6c8-kafka-bootstrap.strimzi.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: "trades"
        #
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
