apiVersion: v1
kind: ConfigMap
metadata:
  name: backfill-technical-indicators
  namespace: services
data:
  KAFKA_BROKER_ADDRESS: "kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092"
  TRADES_TOPIC: "trades_historical_1d"
  CANDLES_TOPIC: "candles_historical_1d"
  TECHNICAL_INDICATORS_TOPIC: "technical_indicators"
  CANDLES_CONSUMER_GROUP: "candles-historical-consumer-group-1d"
  TECHNICAL_INDICATORS_CONSUMER_GROUP: "technical-indicators-historical-consumer-group-1d"
  CANDLE_SECONDS: "60"
  LAST_N_DAYS: "1"
  COUNT_TRADES: "1000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-historical
  namespace: services
  labels:
    app: trades-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades-historical
  template:
    metadata:
      labels:
        app: trades-historical
    spec:
      containers:
      - name: trades-historical
        image: trades:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TRADES_TOPIC
        - name: LIVE_OR_HISTORICAL
          value: "historical"
        - name: LAST_N_DAYS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: LAST_N_DAYS
        - name: COUNT_TRADES
          value: "1000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles-historical
  namespace: services
  labels:
    app: candles-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles-historical
  template:
    metadata:
      labels:
        app: candles-historical
    spec:
      containers:
      - name: candles-historical
        image: candles:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TRADES_TOPIC
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLES_TOPIC
        - name: CANDLE_SECONDS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLE_SECONDS
        - name: KAFKA_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLES_CONSUMER_GROUP
        - name: EMIT_INTERMEDIATE_CANDLES
          value: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators-historical
  namespace: services
  labels:
    app: technical-indicators-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical-indicators-historical
  template:
    metadata:
      labels:
        app: technical-indicators-historical
    spec:
      containers:
      - name: technical-indicators-historical
        image: technical-indicators:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLES_TOPIC
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TECHNICAL_INDICATORS_TOPIC
        - name: KAFKA_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TECHNICAL_INDICATORS_CONSUMER_GROUP
        - name: CANDLE_SECONDS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLE_SECONDS
        - name: RISINGWAVE_HOST
          value: "risingwave.risingwave.svc.cluster.local"
        - name: RISINGWAVE_PORT
          value: "4567"
        - name: RISINGWAVE_USER
          value: "root"
        - name: RISINGWAVE_DATABASE
          value: "dev"
        - name: RISINGWAVE_PASSWORD
          value: "123456"
        - name: RISINGWAVE_TABLE_NAME
          value: "technical_indicators"
