apiVersion: batch/v1
kind: CronJob
metadata:
  name: trades-historical
  namespace: services
spec:
  schedule: "0 0 * * *" # every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: trades-historical
            image: trades:dev
            imagePullPolicy: Never # Use the local image
            env:
            - name: KAFKA_BROKER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: backfill-technical-indicators-config
                  key: KAFKA_BROKER_ADDRESS
            - name: KAFKA_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: backfill-technical-indicators-config
                  key: TRADES_KAFKA_TOPIC_NAME
            - name: KAFKA_CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: backfill-technical-indicators-config
                  key: TRADES_KAFKA_CONSUMER_GROUP
            resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "1000m"
                memory: "2Gi"
